<a href="https://colab.research.google.com/github/Tharun-17/Ethereum/blob/main/Ethereum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary libraries.

In [1]:
import tensorflow
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [2]:
import yfinance as yf
import datetime

Accessing today's date using datetime.

In [3]:
today = datetime.datetime.now()
today
date_today = today.strftime("%Y-%m-%d")

In [4]:
date_today

'2023-07-12'

Using 'ETH-USD' ticker to get data from start date to today.

In [5]:
ticker = 'ETH-USD'
end_date = date_today
start_date = '2015-01-01'

Downloading data and converting it into a pandas dataframe.

In [6]:
df = yf.download(ticker, start = start_date, end = end_date)

[*********************100%***********************]  1 of 1 completed


In [7]:
df

Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-07-07  1847.512573  1876.963257  1832.025391  1870.602539  1870.602539   
2023-07-08  1871.002075  1872.501587  1844.641724  1865.539551  1865.539551   
2023-07-09  1865.594971  1878.668945  1857.748291  1863.009766  1863.009766   
2023-07-10  1863.240234  1905.460815  1848.777222  1880.556396  1880.556396   
2023-07-11  1880.654907  1889.381714  1863.218628  1878.336060  1878.336060   

                Volume  
Date                    
2017-11-09   893249984  
2017-11-10   885985984  
2017-11-11   842300992  
2017-11-12  1613479936  
2017-11-13  1041889984  
...                ...  
2023-07-07  6468885150  
2023-07-08  4299007854  
2023-07-09  4392863807  
2023-07-10  6336468234  
2023-07-11  4905225892  

[2071 rows x 6 columns]

In [8]:
import pandas as pd
data = pd.DataFrame(df)

In [9]:
data

Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-07-07  1847.512573  1876.963257  1832.025391  1870.602539  1870.602539   
2023-07-08  1871.002075  1872.501587  1844.641724  1865.539551  1865.539551   
2023-07-09  1865.594971  1878.668945  1857.748291  1863.009766  1863.009766   
2023-07-10  1863.240234  1905.460815  1848.777222  1880.556396  1880.556396   
2023-07-11  1880.654907  1889.381714  1863.218628  1878.336060  1878.336060   

                Volume  
Date                    
2017-11-09   893249984  
2017-11-10   885985984  
2017-11-11   842300992  
2017-11-12  1613479936  
2017-11-13  1041889984  
...                ...  
2023-07-07  6468885150  
2023-07-08  4299007854  
2023-07-09  4392863807  
2023-07-10  6336468234  
2023-07-11  4905225892  

[2071 rows x 6 columns]

Seperating date column and seperating it into new columns Month,Year and day

In [10]:
data['Date'] = pd.to_datetime(data.index).date

In [11]:
data = data.reset_index(drop=True)
data

Open         High          Low        Close    Adj Close  \
0      308.644989   329.451996   307.056000   320.884003   320.884003   
1      320.670990   324.717987   294.541992   299.252991   299.252991   
2      298.585999   319.453003   298.191986   314.681000   314.681000   
3      314.690002   319.153015   298.513000   307.907990   307.907990   
4      307.024994   328.415009   307.024994   316.716003   316.716003   
...           ...          ...          ...          ...          ...   
2066  1847.512573  1876.963257  1832.025391  1870.602539  1870.602539   
2067  1871.002075  1872.501587  1844.641724  1865.539551  1865.539551   
2068  1865.594971  1878.668945  1857.748291  1863.009766  1863.009766   
2069  1863.240234  1905.460815  1848.777222  1880.556396  1880.556396   
2070  1880.654907  1889.381714  1863.218628  1878.336060  1878.336060   

          Volume        Date  
0      893249984  2017-11-09  
1      885985984  2017-11-10  
2      842300992  2017-11-11  
3     1613479936  2017-11-12  
4     1041889984  2017-11-13  
...          ...         ...  
2066  6468885150  2023-07-07  
2067  4299007854  2023-07-08  
2068  4392863807  2023-07-09  
2069  6336468234  2023-07-10  
2070  4905225892  2023-07-11  

[2071 rows x 7 columns]

In [12]:
data['Month'] = pd.to_datetime(data['Date']).dt.month

In [13]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['day'] = pd.to_datetime(data['Date']).dt.day

In [14]:
data

Open         High          Low        Close    Adj Close  \
0      308.644989   329.451996   307.056000   320.884003   320.884003   
1      320.670990   324.717987   294.541992   299.252991   299.252991   
2      298.585999   319.453003   298.191986   314.681000   314.681000   
3      314.690002   319.153015   298.513000   307.907990   307.907990   
4      307.024994   328.415009   307.024994   316.716003   316.716003   
...           ...          ...          ...          ...          ...   
2066  1847.512573  1876.963257  1832.025391  1870.602539  1870.602539   
2067  1871.002075  1872.501587  1844.641724  1865.539551  1865.539551   
2068  1865.594971  1878.668945  1857.748291  1863.009766  1863.009766   
2069  1863.240234  1905.460815  1848.777222  1880.556396  1880.556396   
2070  1880.654907  1889.381714  1863.218628  1878.336060  1878.336060   

          Volume        Date  Month  Year  day  
0      893249984  2017-11-09     11  2017    9  
1      885985984  2017-11-10     11  2017   10  
2      842300992  2017-11-11     11  2017   11  
3     1613479936  2017-11-12     11  2017   12  
4     1041889984  2017-11-13     11  2017   13  
...          ...         ...    ...   ...  ...  
2066  6468885150  2023-07-07      7  2023    7  
2067  4299007854  2023-07-08      7  2023    8  
2068  4392863807  2023-07-09      7  2023    9  
2069  6336468234  2023-07-10      7  2023   10  
2070  4905225892  2023-07-11      7  2023   11  

[2071 rows x 10 columns]

Using scatter plot to gain insight about closing value throughtout the dataset and analyzing pattern.

In [15]:
px.scatter(data,x=data['Date'],y=data['Close'])

Using color coding for different Years.

In [16]:
px.scatter(data,x=data['Date'],y=data['Close'],color = 'Year')

As the dataset is a timeseries data we are using open, high, lo, close columns for both input and output variables.

In [17]:
x = data[['Open','High','Low','Close']].values
y = data[['Open','High','Low','Close']].values

Splitting the data into training and testing data.

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=180)

In [19]:
n_features = x_train.shape
n_features

(1449, 4)

Creating a LSTM model based on the input and output variables.

In [20]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(120, activation='relu', return_sequences=True, input_shape=(4, 1)))
model.add(LSTM(120, activation='relu'))
model.add(Dense(80, activation='linear'))
model.add(Dense(4, activation='linear'))
model.compile(loss='MeanSquaredError', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=10, batch_size=10, verbose=2)


Epoch 1/10
208/208 - 3s - loss: 127018.5078 - accuracy: 0.6591 - 3s/epoch - 16ms/step
Epoch 2/10
208/208 - 1s - loss: 2405.8772 - accuracy: 0.8199 - 1s/epoch - 6ms/step
Epoch 3/10
208/208 - 2s - loss: 2132.1699 - accuracy: 0.8484 - 2s/epoch - 8ms/step
Epoch 4/10
208/208 - 1s - loss: 2442.7507 - accuracy: 0.8551 - 1s/epoch - 6ms/step
Epoch 5/10
208/208 - 2s - loss: 3553.0811 - accuracy: 0.7764 - 2s/epoch - 8ms/step
Epoch 6/10
208/208 - 2s - loss: 2648.0061 - accuracy: 0.7948 - 2s/epoch - 9ms/step
Epoch 7/10
208/208 - 2s - loss: 2743.6526 - accuracy: 0.8315 - 2s/epoch - 9ms/step
Epoch 8/10
208/208 - 2s - loss: 2539.1646 - accuracy: 0.8320 - 2s/epoch - 10ms/step
Epoch 9/10
208/208 - 3s - loss: 2782.5381 - accuracy: 0.7117 - 3s/epoch - 13ms/step
Epoch 10/10
208/208 - 2s - loss: 2456.3704 - accuracy: 0.7764 - 2s/epoch - 10ms/step


Testing model performance for the testing data.

In [21]:
y_pred = model.predict(x_test)

20/20 [==============================] - 0s 5ms/step


In [22]:
y_pred

array([[ 159.97604,  171.13283,  157.19514,  170.7283 ],
       [1771.9353 , 1906.5953 , 1740.1969 , 1896.574  ],
       [1572.3827 , 1693.0127 , 1545.3861 , 1685.312  ],
       ...,
       [2742.9832 , 2955.2324 , 2696.215  , 2942.597  ],
       [ 443.9077 ,  477.64426,  435.70825,  475.24045],
       [ 593.21466,  638.2307 ,  582.8389 ,  635.4333 ]], dtype=float32)

Reshaping the predicted output into the input(testing data) shape.

In [23]:
y_pred=y_pred.reshape(y_test.shape)

In [24]:
y_test.shape

(622, 4)

In [25]:
y_pred.shape

(622, 4)

Calculating the difference between actual and predicted output.

In [26]:
diff = y_test[:,2:3] - y_pred[:,2:3]

In [27]:
diff

array([[-3.34814453e+00],
       [ 4.82786865e+01],
       [ 2.35987549e+01],
       [ 7.13397217e+00],
       [-1.87305603e+01],
       [ 6.08059692e+00],
       [ 2.43345947e+01],
       [ 2.18275452e+00],
       [ 3.07546387e+01],
       [ 9.54421997e-01],
       [-5.35327148e+01],
       [-5.85676270e+01],
       [-8.78479004e+00],
       [ 4.24346924e+00],
       [ 7.37026367e+01],
       [-1.08251953e+01],
       [ 5.20429688e+01],
       [ 1.84782410e+00],
       [ 3.80683899e-01],
       [ 1.10603333e+00],
       [-3.80687256e+02],
       [ 1.83209229e+01],
       [-2.27580566e+01],
       [ 3.89251709e-01],
       [ 5.48151855e+01],
       [ 4.39003906e+01],
       [-1.65074463e+01],
       [-5.95104980e+00],
       [-8.38867188e+01],
       [-1.01940918e+00],
       [-2.69247437e+01],
       [ 4.12707520e+01],
       [ 3.22851562e+00],
       [ 5.37889404e+01],
       [-2.49159241e+00],
       [ 9.90631104e-01],
       [ 8.88092041e+00],
       [ 6.88569336e+01],
       [-3.1

Plotting te difference using scatter plot.

In [28]:
px.scatter(diff)

In [29]:
n = 10 #n represents the number of days we need forecast for.

In [30]:
last = list(data.iloc[-1,0:4]) #creating a list and adding the last day open, high, low, close values.

In [31]:
model.predict([last]) #predicting the forecast of next day using the last day.

1/1 [==============================] - 0s 49ms/step


array([[1844.5735, 1984.9928, 1812.2509, 1975.1172]], dtype=float32)

In [32]:
forecastn = [last] #ceating a new list forecastn to store the forecast of n days.

predicting for nth day forecast using predicted value of n-1th day.

In [33]:
for i in range(1,n+1):
  forecastn.append(model.predict([forecastn[i-1]]))

1/1 [==============================] - 0s 15ms/step


In [34]:
forecastn

[[1880.6549072265625,
  1889.3817138671875,
  1863.2186279296875,
  1878.3360595703125],
 array([[1844.5735, 1984.9928, 1812.2509, 1975.1172]], dtype=float32),
 array([[1855.4761, 1997.9708, 1821.7439, 1987.5625]], dtype=float32),
 array([[1866.6196, 2009.9609, 1832.5824, 1999.4137]], dtype=float32),
 array([[1877.7964, 2021.9921, 1843.5459, 2011.3748]], dtype=float32),
 array([[1889.0338, 2034.0917, 1854.578 , 2023.409 ]], dtype=float32),
 array([[1900.3354, 2046.2599, 1865.6736, 2035.5131]], dtype=float32),
 array([[1911.7023, 2058.4978, 1876.8335, 2047.6864]], dtype=float32),
 array([[1923.1343, 2070.8062, 1888.0574, 2059.9302]], dtype=float32),
 array([[1934.6312, 2083.1863, 1899.3452, 2072.2449]], dtype=float32),
 array([[1946.1951, 2095.6367, 1910.6986, 2084.6292]], dtype=float32)]

In [35]:
forecastn.pop(0) #Removing the last day values from the forecast.

[1880.6549072265625,
 1889.3817138671875,
 1863.2186279296875,
 1878.3360595703125]

Seperating just closing values from the forecast.

In [36]:
extra = [arr[0][2:3] for arr in forecastn]
extra

[array([1812.2509], dtype=float32),
 array([1821.7439], dtype=float32),
 array([1832.5824], dtype=float32),
 array([1843.5459], dtype=float32),
 array([1854.578], dtype=float32),
 array([1865.6736], dtype=float32),
 array([1876.8335], dtype=float32),
 array([1888.0574], dtype=float32),
 array([1899.3452], dtype=float32),
 array([1910.6986], dtype=float32)]

Converting the numpy values into float values and adding them to a list.

In [37]:
for i in range(len(extra)):
  extra[i] = list(extra[i])

In [38]:
extra1 = [arr[0] for arr in extra]

In [39]:
extra1

[1812.2509,
 1821.7439,
 1832.5824,
 1843.5459,
 1854.578,
 1865.6736,
 1876.8335,
 1888.0574,
 1899.3452,
 1910.6986]

Closing value of the nth day based on the forecast.

In [40]:
print(extra1[-1])

1910.6986


In [41]:
px.line(x=extra1)